export const ActionTypes = {
    SET_IS_NAME_SETTED: 'SET_IS_NAME_SETTED',
    SET_IS_QUESTION_RUNNING: 'SET_IS_QUESTION_RUNNING',
    SET_IS_DISABLED: 'SET_IS_DISABLED',
    SET_SESSION_RECOVERY: 'SET_SESSION_RECOVERY',
    SET_IS_CLOCK_INPUT: 'SET_IS_CLOCK_INPUT',
    SET_IS_INPUT: 'SET_IS_INPUT',
    SET_IS_THERE_A_WINNER: 'SET_IS_THERE_A_WINNER',
    SET_JOINED_QUIZ: 'SET_JOINED_QUIZ',
    SET_IS_MASTER_ONLINE: 'SET_IS_MASTER_ONLINE',
    SET_SHOW_SCORES: 'SET_SHOW_SCORES',
};
