export const initialState = {
    quizData: null,
    question: null,
    playerData: [],
    clickedResponses: {},
    initialPlayerData: [],
    nickName: '',
    isNameSetted: false,
    _joinedQuiz: false,
    socket: null,
    error: null,
    shuffledQuestionResponses: null,
    isQuestionRunning: false,
    questionsToDelete: [],
    timeLeft: null,
    showScores: false,
    isDisabled: true,
    sessionRecovery: true,
    sessionTime: 0,
    sessionTimeLeft: 0,
    connectedClients: 0,
    isMasterOnline: false,
    questionsExecuted: [],
    isThereAWinner: false,
    isClockInput: false,
    isInput: false,
};
