export const initialState = {
    question: null,
    clickedResponses: {},
    nickName: '',
    isNameSetted: false,
    _joinedQuiz: false,
    socket: null,
    error: null,
    isQuestionRunning: false,
    questionsToDelete: [],
    timeLeft: null,
    showScores: false,
    isDisabled: true,
    sessionRecovery: true,
    sessionTime: 0,
    sessionTimeLeft: 0,
    connectedClients: 0,
    isMasterOnline: false,
    isThereAWinner: false,
    isClockInput: false,
    isInput: false,
};
